name: flutter_app
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  css_colors: ^1.0.2
  fl_chart: ^0.11.1
  font_awesome_flutter: ^8.8.1
  circular_menu: ^1.1.2
  table_calendar: ^2.2.3
  mongo_dart: ^0.4.4
  expansion_card: ^0.1.0
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  lint: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-R.ttf
        - asset: fonts/Ubuntu-RI.ttf
          style: italic